### ISSUE TITLE
dead code / broken ante

### ISSUE THREAD

**Issue by ashuntwo** [pixelmonaskarion/poker#4]
https://github.com/pixelmonaskarion/poker/blob/5f1b799b0286067bdb194050ec2dfe787029290b/src/main/java/poker/game/Game.java#L132

your code says:
if(roundState == 0) {
...
} else if(roundState == 0) {
...
}

The second clause should never run. What am i missing?

**Comment by pixelmonaskarion** [comment]
removed the dead code, it was from the offline mode
